export const schema = {
 branches:{label:'Филиалы',singular:'филиал',icon:'Building2',fields:[['branch_id','ID','id'],['branch_name','Название','text'],['swift_code','SWIFT-код','text'],['city','Город','text'],['address','Адрес','text'],['phone','Телефон','tel'],['created_at','Создан','datetime']]},
 employees:{label:'Сотрудники',singular:'сотрудника',icon:'BriefcaseBusiness',fields:[['employee_id','ID','id'],['branch_id','Филиал','ref:branches'],['first_name','Имя','text'],['last_name','Фамилия','text'],['position','Должность','text'],['salary','Зарплата','number'],['email','Email','email'],['hire_date','Дата найма','date'],['is_active','Активен','boolean']]},
 customers:{label:'Клиенты',singular:'клиента',icon:'UsersRound',fields:[['customer_id','ID','id'],['first_name','Имя','text'],['last_name','Фамилия','text'],['national_id','ИИН / ID','text'],['date_of_birth','Дата рождения','date'],['phone','Телефон','tel'],['email','Email','email'],['address','Адрес','text'],['created_at','Создан','datetime']]},
 accounts:{label:'Счета',singular:'счёт',icon:'WalletCards',fields:[['account_id','ID','id'],['branch_id','Филиал','ref:branches'],['account_number','Номер счёта','text'],['account_type','Тип','select:Текущий|Сберегательный|Бизнес'],['balance','Баланс','number'],['currency','Валюта','select:KZT|USD|EUR'],['status','Статус','select:Активен|Заблокирован|Закрыт'],['opened_at','Открыт','datetime'],['closed_at','Закрыт','datetime']]},
 account_holders:{label:'Владельцы счетов',singular:'владельца',icon:'UserRoundCheck',fields:[['account_id','Счёт','ref:accounts'],['customer_id','Клиент','ref:customers'],['ownership_percent','Доля владения, %','number'],['added_at','Добавлен','datetime']]},
 transactions:{label:'Транзакции',singular:'транзакцию',icon:'ArrowLeftRight',fields:[['transaction_id','ID','id'],['from_account_id','Счёт отправителя','ref:accounts'],['to_account_id','Счёт получателя','ref:accounts'],['transaction_type','Тип','select:Перевод|Пополнение|Снятие|Платёж'],['amount','Сумма','number'],['status','Статус','select:Выполнено|В обработке|Отклонено'],['description','Описание','text'],['transaction_date','Дата операции','datetime']]},
 transfers:{label:'Переводы',singular:'перевод',icon:'Send',fields:[['transfer_id','ID','id'],['transfer_type','Тип','select:Внутренний|Межбанковский|Криптовалюта'],['from_account_id','Откуда','ref:accounts'],['to_account_id','Куда','ref:accounts'],['currency','Валюта','select:KZT|USD|EUR|USDT'],['amount','Сумма','number'],['fee','Комиссия','number'],['network','Сеть','text'],['wallet_address','Адрес кошелька','text'],['tx_hash','Хэш транзакции','text'],['status','Статус','select:Выполнено|В обработке|Отклонено'],['created_at','Создан','datetime'],['completed_at','Завершён','datetime']]},
 loans:{label:'Кредиты',singular:'кредит',icon:'Landmark',fields:[['loan_id','ID','id'],['customer_id','Клиент','ref:customers'],['branch_id','Филиал','ref:branches'],['approved_by','Одобрил','ref:employees'],['principal_amount','Сумма кредита','number'],['interest_rate','Ставка, %','number'],['term_months','Срок, месяцев','number'],['status','Статус','select:На рассмотрении|Активен|Погашен|Отклонён'],['application_date','Дата заявки','date'],['start_date','Начало','date'],['end_date','Окончание','date']]},
 loan_payments:{label:'Платежи по кредитам',singular:'платёж',icon:'ReceiptText',fields:[['payment_id','ID','id'],['loan_id','Кредит','ref:loans'],['account_id','Счёт','ref:accounts'],['amount','Сумма','number'],['payment_date','Дата платежа','datetime'],['payment_number','Номер платежа','number'],['is_late','Просрочен','boolean']]},
 bank_shareholders:{label:'Акционеры',singular:'акционера',icon:'PieChart',fields:[['shareholder_id','ID','id'],['full_name','ФИО / компания','text'],['holder_type','Тип владельца','select:Физическое лицо|Компания'],['country','Страна','text'],['share_percent','Доля, %','number'],['shares_count','Количество акций','number'],['acquired_at','Дата приобретения','date'],['added_at','Добавлен','datetime'],['customer_id','Клиент','ref:customers']]}
};
export const seed = {
 branches:[{branch_id:1,branch_name:'Центральный офис',swift_code:'NSBKKZKX',city:'Алматы',address:'пр. Аль-Фараби, 77',phone:'+7 727 300 11 00',created_at:'2022-03-12T09:00'},{branch_id:2,branch_name:'Астана',swift_code:'NSBKKZK2',city:'Астана',address:'ул. Достык, 18',phone:'+7 717 255 20 20',created_at:'2023-06-01T10:00'},{branch_id:3,branch_name:'Шымкент',swift_code:'NSBKKZK3',city:'Шымкент',address:'пр. Тауке хана, 25',phone:'+7 725 244 33 22',created_at:'2024-01-15T09:00'}],
 employees:[{employee_id:1,branch_id:1,first_name:'Айгерим',last_name:'Садыкова',position:'Менеджер',salary:520000,email:'a.sadykova@northstar.kz',hire_date:'2022-04-03',is_active:true},{employee_id:2,branch_id:2,first_name:'Данияр',last_name:'Омаров',position:'Кредитный специалист',salary:460000,email:'d.omarov@northstar.kz',hire_date:'2023-07-18',is_active:true},{employee_id:3,branch_id:1,first_name:'Мадина',last_name:'Ермекова',position:'Операционист',salary:380000,email:'m.ermekova@northstar.kz',hire_date:'2024-02-10',is_active:true}],
 customers:[{customer_id:1,first_name:'Алина',last_name:'Касымова',national_id:'950418400123',date_of_birth:'1995-04-18',phone:'+7 701 234 56 78',email:'alina@example.com',address:'Алматы, ул. Абая, 12',created_at:'2025-02-12T11:20'},{customer_id:2,first_name:'Тимур',last_name:'Ахметов',national_id:'900721300456',date_of_birth:'1990-07-21',phone:'+7 777 555 21 00',email:'timur@example.com',address:'Астана, ул. Кунаева, 9',created_at:'2025-04-08T14:30'},{customer_id:3,first_name:'Диана',last_name:'Нурланова',national_id:'981130400789',date_of_birth:'1998-11-30',phone:'+7 705 122 88 90',email:'diana@example.com',address:'Алматы, ул. Панфилова, 40',created_at:'2026-01-19T10:15'},{customer_id:4,first_name:'Арман',last_name:'Жумабаев',national_id:'920109300321',date_of_birth:'1992-01-09',phone:'+7 702 999 45 00',email:'arman@example.com',address:'Шымкент, ул. Байтурсынова, 7',created_at:'2026-03-06T12:10'}],
 accounts:[{account_id:1,branch_id:1,account_number:'KZ12001A000000000001',account_type:'Текущий',balance:2450800,currency:'KZT',status:'Активен',opened_at:'2025-02-12T12:00',closed_at:''},{account_id:2,branch_id:2,account_number:'KZ12001A000000000002',account_type:'Сберегательный',balance:8750000,currency:'KZT',status:'Активен',opened_at:'2025-04-08T15:00',closed_at:''},{account_id:3,branch_id:1,account_number:'KZ12001A000000000003',account_type:'Текущий',balance:12340,currency:'USD',status:'Активен',opened_at:'2026-01-19T11:00',closed_at:''},{account_id:4,branch_id:3,account_number:'KZ12001A000000000004',account_type:'Бизнес',balance:6342000,currency:'KZT',status:'Заблокирован',opened_at:'2026-03-06T13:00',closed_at:''}],
 account_holders:[{account_id:1,customer_id:1,ownership_percent:100,added_at:'2025-02-12T12:00'},{account_id:2,customer_id:2,ownership_percent:100,added_at:'2025-04-08T15:00'},{account_id:3,customer_id:3,ownership_percent:100,added_at:'2026-01-19T11:00'},{account_id:4,customer_id:4,ownership_percent:75,added_at:'2026-03-06T13:00'},{account_id:4,customer_id:2,ownership_percent:25,added_at:'2026-03-06T13:00'}],
 transactions:[{transaction_id:1,from_account_id:1,to_account_id:2,transaction_type:'Перевод',amount:125000,status:'Выполнено',description:'Оплата услуг',transaction_date:'2026-09-29T14:24'},{transaction_id:2,from_account_id:2,to_account_id:3,transaction_type:'Перевод',amount:48000,status:'В обработке',description:'Перевод между счетами',transaction_date:'2026-09-29T11:18'},{transaction_id:3,from_account_id:4,to_account_id:1,transaction_type:'Платёж',amount:320000,status:'Отклонено',description:'Оплата счёта',transaction_date:'2026-09-28T16:42'},{transaction_id:4,from_account_id:1,to_account_id:4,transaction_type:'Перевод',amount:76000,status:'Выполнено',description:'Возврат средств',transaction_date:'2026-09-27T09:12'}],
 transfers:[{transfer_id:1,transfer_type:'Внутренний',from_account_id:1,to_account_id:2,currency:'KZT',amount:125000,fee:0,network:'',wallet_address:'',tx_hash:'',status:'Выполнено',created_at:'2026-09-29T14:23',completed_at:'2026-09-29T14:24'},{transfer_id:2,transfer_type:'Межбанковский',from_account_id:2,to_account_id:3,currency:'USD',amount:1000,fee:10,network:'SWIFT',wallet_address:'',tx_hash:'',status:'В обработке',created_at:'2026-09-29T11:17',completed_at:''}],
 loans:[{loan_id:1,customer_id:1,branch_id:1,approved_by:1,principal_amount:3500000,interest_rate:14.5,term_months:36,status:'Активен',application_date:'2025-05-01',start_date:'2025-05-10',end_date:'2028-05-10'},{loan_id:2,customer_id:2,branch_id:2,approved_by:2,principal_amount:12000000,interest_rate:12.9,term_months:60,status:'Активен',application_date:'2025-08-11',start_date:'2025-08-20',end_date:'2030-08-20'},{loan_id:3,customer_id:4,branch_id:3,approved_by:'',principal_amount:2100000,interest_rate:17.2,term_months:24,status:'На рассмотрении',application_date:'2026-09-25',start_date:'',end_date:''}],
 loan_payments:[{payment_id:1,loan_id:1,account_id:1,amount:119500,payment_date:'2026-09-10T10:00',payment_number:16,is_late:false},{payment_id:2,loan_id:2,account_id:2,amount:275000,payment_date:'2026-09-22T12:00',payment_number:13,is_late:false},{payment_id:3,loan_id:1,account_id:1,amount:119500,payment_date:'2026-08-14T10:00',payment_number:15,is_late:true}],
 bank_shareholders:[{shareholder_id:1,full_name:'Northstar Holding',holder_type:'Компания',country:'Казахстан',share_percent:65,shares_count:650000,acquired_at:'2022-03-01',added_at:'2022-03-12T09:00',customer_id:''},{shareholder_id:2,full_name:'Тимур Ахметов',holder_type:'Физическое лицо',country:'Казахстан',share_percent:20,shares_count:200000,acquired_at:'2023-08-11',added_at:'2023-08-11T10:00',customer_id:2},{shareholder_id:3,full_name:'Orion Capital',holder_type:'Компания',country:'Сингапур',share_percent:15,shares_count:150000,acquired_at:'2024-04-07',added_at:'2024-04-07T10:00',customer_id:''}]
};
export const primaryKey = (entity) => schema[entity].fields.find(f=>f[2]==='id')?.[0];
export const rowKey = (entity,row) => primaryKey(entity) ? String(row[primaryKey(entity)]) : `${row.account_id}:${row.customer_id}`;
